import { Game } from './game';

export const GAMES: Game[] = [
    {
        "GameDate": "Thu, 25 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "ORL",
        "HomeTeamFullName": "Orlando Magic",
        "HomeTeamID": 22,
        "HomeTeamScore": 114,
        "ID": 64,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "POR",
        "VisitorTeamFullName": "Portland Trail Blazers",
        "VisitorTeamID": 25,
        "VisitorTeamScore": 128
    },
    {
        "GameDate": "Thu, 25 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "LAL",
        "HomeTeamFullName": "Los Angeles Lakers",
        "HomeTeamID": 14,
        "HomeTeamScore": 121,
        "ID": 66,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "DEN",
        "VisitorTeamFullName": "Denver Nuggets",
        "VisitorTeamID": 8,
        "VisitorTeamScore": 114
    },
    {
        "GameDate": "Fri, 26 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "CHA",
        "HomeTeamFullName": "Charlotte Hornets",
        "HomeTeamID": 4,
        "HomeTeamScore": 135,
        "ID": 67,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "CHI",
        "VisitorTeamFullName": "Chicago Bulls",
        "VisitorTeamID": 5,
        "VisitorTeamScore": 106
    },
    {
        "GameDate": "Fri, 26 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "NYK",
        "HomeTeamFullName": "New York Knicks",
        "HomeTeamID": 20,
        "HomeTeamScore": 100,
        "ID": 68,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "GSW",
        "VisitorTeamFullName": "Golden State Warriors",
        "VisitorTeamID": 10,
        "VisitorTeamScore": 128
    },
    {
        "GameDate": "Fri, 26 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "TOR",
        "HomeTeamFullName": "Toronto Raptors",
        "HomeTeamID": 28,
        "HomeTeamScore": 116,
        "ID": 69,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "DAL",
        "VisitorTeamFullName": "Dallas Mavericks",
        "VisitorTeamID": 7,
        "VisitorTeamScore": 107
    },
    {
        "GameDate": "Fri, 26 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "HOU",
        "HomeTeamFullName": "Houston Rockets",
        "HomeTeamID": 11,
        "HomeTeamScore": 113,
        "ID": 70,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "LAC",
        "VisitorTeamFullName": "LA Clippers",
        "VisitorTeamID": 13,
        "VisitorTeamScore": 133
    },
    {
        "GameDate": "Fri, 26 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "MIN",
        "HomeTeamFullName": "Minnesota Timberwolves",
        "HomeTeamID": 18,
        "HomeTeamScore": 95,
        "ID": 71,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "MIL",
        "VisitorTeamFullName": "Milwaukee Bucks",
        "VisitorTeamID": 17,
        "VisitorTeamScore": 125
    },
    {
        "GameDate": "Fri, 26 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "NOP",
        "HomeTeamFullName": "New Orleans Pelicans",
        "HomeTeamID": 19,
        "HomeTeamScore": 117,
        "ID": 72,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "BKN",
        "VisitorTeamFullName": "Brooklyn Nets",
        "VisitorTeamID": 3,
        "VisitorTeamScore": 115
    },
    {
        "GameDate": "Fri, 26 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "SAC",
        "HomeTeamFullName": "Sacramento Kings",
        "HomeTeamID": 26,
        "HomeTeamScore": 116,
        "ID": 73,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "WAS",
        "VisitorTeamFullName": "Washington Wizards",
        "VisitorTeamID": 30,
        "VisitorTeamScore": 112
    },
    {
        "GameDate": "Sat, 27 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "DET",
        "HomeTeamFullName": "Detroit Pistons",
        "HomeTeamID": 9,
        "HomeTeamScore": 89,
        "ID": 74,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "BOS",
        "VisitorTeamFullName": "Boston Celtics",
        "VisitorTeamID": 2,
        "VisitorTeamScore": 109
    },
    {
        "GameDate": "Sat, 27 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "NOP",
        "HomeTeamFullName": "New Orleans Pelicans",
        "HomeTeamID": 19,
        "HomeTeamScore": 111,
        "ID": 75,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "UTA",
        "VisitorTeamFullName": "Utah Jazz",
        "VisitorTeamID": 29,
        "VisitorTeamScore": 132
    },
    {
        "GameDate": "Sat, 27 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "CLE",
        "HomeTeamFullName": "Cleveland Cavaliers",
        "HomeTeamID": 6,
        "HomeTeamScore": 107,
        "ID": 76,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "IND",
        "VisitorTeamFullName": "Indiana Pacers",
        "VisitorTeamID": 12,
        "VisitorTeamScore": 119
    },
    {
        "GameDate": "Sat, 27 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "ATL",
        "HomeTeamFullName": "Atlanta Hawks",
        "HomeTeamID": 1,
        "HomeTeamScore": 85,
        "ID": 77,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "CHI",
        "VisitorTeamFullName": "Chicago Bulls",
        "VisitorTeamID": 5,
        "VisitorTeamScore": 97
    },
    {
        "GameDate": "Sat, 27 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "PHI",
        "HomeTeamFullName": "Philadelphia 76ers",
        "HomeTeamID": 23,
        "HomeTeamScore": 105,
        "ID": 78,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "CHA",
        "VisitorTeamFullName": "Charlotte Hornets",
        "VisitorTeamID": 4,
        "VisitorTeamScore": 103
    },
    {
        "GameDate": "Sat, 27 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "MIA",
        "HomeTeamFullName": "Miami Heat",
        "HomeTeamID": 16,
        "HomeTeamScore": 120,
        "ID": 79,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "POR",
        "VisitorTeamFullName": "Portland Trail Blazers",
        "VisitorTeamID": 25,
        "VisitorTeamScore": 111
    },
    {
        "GameDate": "Sat, 27 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "MEM",
        "HomeTeamFullName": "Memphis Grizzlies",
        "HomeTeamID": 15,
        "HomeTeamScore": 117,
        "ID": 80,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "PHX",
        "VisitorTeamFullName": "Phoenix Suns",
        "VisitorTeamID": 24,
        "VisitorTeamScore": 96
    },
    {
        "GameDate": "Sat, 27 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "MIL",
        "HomeTeamFullName": "Milwaukee Bucks",
        "HomeTeamID": 17,
        "HomeTeamScore": 113,
        "ID": 81,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "ORL",
        "VisitorTeamFullName": "Orlando Magic",
        "VisitorTeamID": 22,
        "VisitorTeamScore": 91
    },
    {
        "GameDate": "Sat, 27 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "SAS",
        "HomeTeamFullName": "San Antonio Spurs",
        "HomeTeamID": 27,
        "HomeTeamScore": 110,
        "ID": 82,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "LAL",
        "VisitorTeamFullName": "Los Angeles Lakers",
        "VisitorTeamID": 14,
        "VisitorTeamScore": 106
    },
    {
        "GameDate": "Sun, 28 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "DAL",
        "HomeTeamFullName": "Dallas Mavericks",
        "HomeTeamID": 7,
        "HomeTeamScore": 104,
        "ID": 83,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "UTA",
        "VisitorTeamFullName": "Utah Jazz",
        "VisitorTeamID": 29,
        "VisitorTeamScore": 113
    },
    {
        "GameDate": "Sun, 28 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "BKN",
        "HomeTeamFullName": "Brooklyn Nets",
        "HomeTeamID": 3,
        "HomeTeamScore": 114,
        "ID": 84,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "GSW",
        "VisitorTeamFullName": "Golden State Warriors",
        "VisitorTeamID": 10,
        "VisitorTeamScore": 120
    },
    {
        "GameDate": "Sun, 28 Oct 2018 00:00:00 GMT",
        "GameTime": "NULL",
        "HomeTeamAbbr": "OKC",
        "HomeTeamFullName": "Oklahoma City Thunder",
        "HomeTeamID": 21,
        "HomeTeamScore": 117,
        "ID": 85,
        "Period": 4,
        "PostSeason": 0,
        "Season": 2018,
        "Status": "Final",
        "VisitorTeamAbbr": "PHX",
        "VisitorTeamFullName": "Phoenix Suns",
        "VisitorTeamID": 24,
        "VisitorTeamScore": 110
    }
];